### ISSUE TITLE
Please add support for Ubuntu! 

### ISSUE THREAD

**Issue by marcemira** [pdud/ember-cli-build-notifications#1]
Here is some information:

http://developer.ubuntu.com/en/apps/platform/guides/push-notifications-server-guide/

Awesome men! thanks!

**Comment by tchak** [comment]
Linux support should be solved by #2 . If not, you should talk with `node-notifier` guys.

**Comment by pdud** [comment]
Thanks to @tchak Ubuntu support should be all set!

@marcemira - Could you can take a screenshot to put on the readme?

**Comment by marcemira** [comment]
Thanks! This feature rocks! :+1:
