### ISSUE TITLE
Notify when app finishes reloading

### ISSUE THREAD

**Issue by lolmaus** [pdud/ember-cli-build-notifications#16]
Thank you for the wonderful addon! Let me describe my use case. I believe, it's typical for most Ember coders.

When I edit the code and save, I want to know when my app livereloads and **finishes loading routes**, so that I can open the tab and inspect the result.

The time the app takes to reload is not enough to do something productive (switching contexts is expensive), but enough to be bored to death, especially when you code in short cycles. So I often switch to Twitter or funny cat pics while the app is building and reloading. It also helps depressurize the brain.

The problem here is that I keep relaxing after the app finishes loading and it takes me a while to realize I'm distracted. **I need a notification that would tell me that I can get back to work**. The `buildSuccess` notification doesn't help, because after a successful build a large app still takes a lot of time to reload.

I'm sure I'm not the only Ember developer having this problem.

I'm not sure how this can be approached, and it's probably out of scope of the addon. But as this addon provides access to notifications, I post this feature request here.

Probably we need to run a dev server, similar to livereload or code coverage reporting. The server has to be poked when all routes have finished their `afterModel` hooks, or something like that. Let's discuss possible implementations.

**Comment by pdud** [comment]
Hi lolmaus - thank you for the kind words!

I don't want to keep you from the cat pics 😂 but how about using the browser's Notification API?

You could add something like this into routes you're working on or reopen `Ember.Route`.

```javascript
import Ember from 'ember';
import config from '../config/environment';

const {
  Mixin,
  run
} = Ember;

let ShowtimeMixin;

if (config.environment === 'development') {
  ShowtimeMixin = Mixin.create({
    afterModel(_model, transition) {
      this._super(...arguments);
      if (this._isShowtime(transition)) {
        this.showtime();
      }
    },

    _isShowtime(transition) {
      let { sequence, targetName } = transition;
      let isFirstTransition = sequence === 0;
      let isTargetRoute = targetName === this.routeName;

      if (isFirstTransition && isTargetRoute) {
        this._showtime();
      }
    },

    _showtime() {
      if (typeof Notification === 'undefined') {
        return;
      }
      if (Notification.permission === 'granted') {
        this._sendShowtimeNotification();
      } else if (Notification.permission !== 'denied') {
        Notification.requestPermission((permission) => {
          if (permission === 'granted') {
            this._sendShowtimeNotification();
          }
        });
      }
    },

    _sendShowtimeNotification() {
      let notification = new Notification('It\'s showtime!');
      run.later(this, () => {
        notification.close();
      }, 3000);
    }
  });
} else {
  ShowtimeMixin = Mixin.create();
}

export default ShowtimeMixin;
```

**Comment by devinrhode2** [comment]
Hot reloading can greatly help https://github.com/toranb/ember-cli-hot-loader

**Comment by devinrhode2** [comment]
Would love to get a notification when the build finishes for `ember server`, although it actually takes longer for me for the app to load.
