### ISSUE TITLE
Getting `NaNms` when upgrading to latest ember (2.10.1)

### ISSUE THREAD

**Issue by Duder-onomy** [pdud/ember-cli-build-notifications#17]
Hi! Great tool! Love it!

I just upgraded an app to ember 2.10.1 and I am now getting some funny business in my notifications.  

It looks like:
![nan-ember-cli-build-notifications](https://cloud.githubusercontent.com/assets/1612785/21334463/a14cd798-c60c-11e6-9371-5160b6832570.png)

I suspect this is because the build are so fast now from 2.10.1 that it cannot even be measured.

Let me know if there is anything I can do to help!

**Comment by Duder-onomy** [comment]
On further investigation, the `results` object that is passed to this:
https://github.com/pdud/ember-cli-build-notifications/blob/master/index.js#L19

looks like: 
```javascript
{ 
    directory: '...some dir',
    graph: Node:0 subtrees: 1 
}
```

Further down that pathway, this code calls:
```javascript
message: 'Build Time: ' + Math.round(results.totalTime/1000000) + 'ms',
```
here: https://github.com/pdud/ember-cli-build-notifications/blob/master/lib/notifier.js#L13

The results object does not have a `totalTime` property and thus, `undefined / 1000000 == NAN`

Let me know next steps if I can do anything to help.

**Comment by pdud** [comment]
Hi @Duder-onomy - thanks for reporting.

I can reproduce the issue too. It looks like this is something the ember-cli team are working on - improving messages throughout the app. Even on canary no build time is available.

How about we show a different message if totalTime is not available?

**Comment by Duder-onomy** [comment]
Correct me if I am wrong, but it seems like a fix for this was just merged and should be available in Canary soon? 

This PR: https://github.com/ember-cli/ember-cli/pull/6546

So, if we have patience, this might just fix itself?

I think we should just leave this ticket open until we are back in action? 
So that others getting here see that it is a known issue and we are waiting on a fix to make it into stable.

**Comment by pdud** [comment]
Hey @Duder-onomy - nice find! I believe updating to Canary would include this code but it still wasn't working. I didn't see anything time related in the object returned.

At the same time its perhaps something they are tweaking so patience could be a good option.

I'm on board with leaving this ticket open and keeping an eye on things. We could have a better fallback if time is not available but at least it doesn't stop the build from succeeding.

**Comment by fusion2004** [comment]
This seems to still be the case on my app running Ember 3.1.

**Comment by pdud** [comment]
Hey @kevinansfield! Thank you for your interest in helping fix this!

I think we may want to wait until the RFC is pushed further along before we make a change like this - https://github.com/emberjs/rfcs/pull/328.

Another way to get the total time is using the existing hook. As mentioned by people above the results object returns `directory` and `graph`. `results.graph.__heimdall__` can be used to calculate the buildTime using this from ember-cli. https://github.com/ember-cli/ember-cli/blob/v3.2.0-beta.1/lib/models/instrumentation.js#L262,L292. I do have a branch that works this way.

There is also an instrumentation hook that can be enabled in `.ember-cli` that we could hook into which I believe has the buildTime.

Maybe the ember-cli team will be willing to restore access to buildTime/ guide us to the best way of getting this info :)

**Comment by pdud** [comment]
If you point to this branch you can get build time restored. We'll see how that RFC goes before merging this in because the timing code is pulled from ember-cli's code base.

https://github.com/pdud/ember-cli-build-notifications/tree/pd-total-time
