### ISSUE TITLE
ember-cli-babel 5.x is deprecated

### ISSUE THREAD

**Issue by elwayman02** [pdud/ember-cli-build-notifications#20]
`DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: ember-cli-build-notifications -> ember-cli-babel`

**Comment by elwayman02** [comment]
Never mind, it looks like this addon was updated but a new release wasn't cut for the latest changes.

**Comment by pdud** [comment]
Just published a new version 0.3.0 that should fix this. Thanks for reporting! :)
