### ISSUE TITLE
Test support?

### ISSUE THREAD

**Issue by toranb** [pdud/ember-cli-build-notifications#6]
Does this also work w/ the testing setup in ember-cli? ie- will it show you a failure for unit or acceptance tests?

If so -what do I need to add to get this working w/ the test setup?

**Comment by pdud** [comment]
Unfortunately this does not show a failure for tests. However, if you have a syntax error that stops tests from running, such as unclosed handlebars `{{` or missing `,`, this addon will send a notification.

It looks like the ember-qunit-notifications are set up to show as OS X Notifications but Chrome forces it's own notification system (I can't find a way to disable it in favor of system notifications).

Safari will show ember-qunit-notifications like this (it appears like you [can't overwrite the icon or 'from localhost' line](https://developer.apple.com/library/mac/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/LocalNotifications/LocalNotifications.html#//apple_ref/doc/uid/TP40012932-SW6)).

![safari](https://cloud.githubusercontent.com/assets/435890/6249976/cb8c07aa-b758-11e4-86df-7a9bfae35560.png)

Firefox Developer Edition looks like this.

![firefox](https://cloud.githubusercontent.com/assets/435890/6249979/d0e47f2a-b758-11e4-8f18-d847ecb2ecd8.png)

Looking forward to your talk at Ember Conf :grin:

**Comment by toranb** [comment]
Thanks for the quick reply! I'll checkout the qunit project (hoping something like this works without chrome as I'm trying to find a tmux /vim friendly OSX notification setup)

Let's chat more in person at EmberConf !!!
